services:
  onemcserver:
    image: ghcr.io/koboshchan/onemcserver:main
    build:
      context: .
    ports:
      - 25565:25565
    volumes:
      - ./config.json:/app/config.json:ro
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    # No ports exposed, no auth by default
    volumes:
      - ./mongodb_data:/data/db
